#!/bin/bash
# Script per forzare Home Assistant a ricaricare l'integrazione pulita

echo "=========================================="
echo "Script di pulizia cache HA per Climate Control Calendar"
echo "=========================================="
echo ""
echo "IMPORTANTE: Esegui questo script SUL TUO SERVER Home Assistant"
echo ""
echo "Passi da seguire:"
echo ""
echo "1. Ferma Home Assistant:"
echo "   ha core stop"
echo ""
echo "2. Rimuovi TUTTA la cache Python:"
echo "   rm -rf /config/custom_components/climate_control_calendar/__pycache__"
echo "   find /config/custom_components/climate_control_calendar -name '*.pyc' -delete"
echo ""
echo "3. Verifica che il file config_flow.py sia quello giusto:"
echo "   grep -n 'return ClimateControlCalendarOptionsFlow()' /config/custom_components/climate_control_calendar/config_flow.py"
echo "   # DEVE mostrare linea 279 SENZA parametri"
echo ""
echo "4. Verifica la versione nel manifest:"
echo "   grep version /config/custom_components/climate_control_calendar/manifest.json"
echo "   # DEVE mostrare 1.0.2"
echo ""
echo "5. Se le verifiche falliscono, aggiorna manualmente i file da HACS o Git:"
echo "   # Oppure copia manualmente dal branch: claude/start-refactoring-plan-ZViBo"
echo ""
echo "6. Riavvia Home Assistant:"
echo "   ha core restart"
echo ""
echo "7. Verifica i log dopo il riavvio:"
echo "   tail -f /config/home-assistant.log | grep climate_control_calendar"
echo ""
echo "=========================================="
